server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/im?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml
  type-aliases-package: geektime.im.lecture.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

websocket:
  connector:
    server:
      readIdleSecond: 0
      writeIdleSecond: 0
      allIdleSecond: 360
      sendBuff: -1
      recvBuff: -1
      backlog: 500000
      bossThreads: 1
      connTimeoutMills: 10000
      soLinger: 0
      port: 8080
      reuseAddr: true
      useDirectBuffer: true
      useEpoll: true
      useMemPool: true
      userThreads: 50
      workerThreads: 0
      idleTimes: 5